Async module loading
concierge/kpm pull request #14
Opened 2017-07-08 03:04 UTC by mrkno

Changes for https://github.com/concierge/Concierge/pull/270

2017-07-11 06:42 UTC, Awarua- requested changes

2017-07-11 06:42 UTC, Awarua- commented on src/types/03-npm.js
>      catch(e) {}
Should not leave exception unhandled, or at least log it

2017-07-11 20:48 UTC, mrkno commented on src/types/03-npm.js
>      catch(e) {}
And log what exactly? This is a copy if exists operation, we don't really care if it fails as long as it tried

2017-07-12 07:21 UTC, Awarua- approved these changes

2017-07-12 09:29 UTC, merged